### ISSUE TITLE
UPGRADE SilverStripe 4 compatability

### ISSUE THREAD

**Issue by muskie9** [webfox/silverstripe-blog-search#4]

**Comment by SUTHERLANDesign** [comment]
Watching this space... keen to use it for SS4.1.0.... for my project.

**Comment by muskie9** [comment]
I have an initial upgrade ready. I'll open a PR against master but a 1.0 branch should be made to preserve the 3.x compatibility.

**Comment by hailwood** [comment]
Hey @muskie9 ,
I've fired you through a DM on the SS slack channel, Can you please check that in the near future?

**Comment by SUTHERLANDesign** [comment]
Thanks guys for quick turn around to get this working for SilverStripe 4. :+1:

**Comment by SUTHERLANDesign** [comment]
@hailwood Is there anyway to add tags into the blog search? it doesn't pick up all the tags at all.

**Comment by hailwood** [comment]
Hey @buffy999,

@muskie9 has taken over this project from the SS4 compatibility side so he'd be the best person to ask as we're not yet using SS4 for anything at webfox, But Assuming SS4 relations work the same as their SS3 counterparts it's likely as simple as [adding a filter on Tags.Title here](https://github.com/webfox/silverstripe-blog-search/blob/master/src/Extensions/BlogSearchBlogExtension.php#L34).

If you wanted to give that a go and submit a pull request we'll get that merged in for you!

**Comment by SUTHERLANDesign** [comment]
Hi @hailwood, i've just managed to get the tag to work! thanks for your help on that, all i did was add this bit into that php file you've suggested:
'Tags.Title:PartialMatch' => Convert::raw2sql($searchParam),

I've never done this before, how do submit a pull request? i'm new on the GitHub at this stage.

**Comment by hailwood** [comment]
@buffy999 good job!

So it's pretty easy! You click the "fork" button in the top right, and it will copy the repository to your account,

From there you clone the repository to your machine, make the change to the file, and the git add/commit/push back up to the repository.

From there github have some official instructions which explain far better than I ever could on how to submit a pull request! https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Because you're just editing one file, there's a bit of an easier way!
On that link to the file I gave you, at the top you'll see there's an edit button, you can just click that, edit the file in the online editor, and github will automatically fork the repository to your account and prompt you to submit the pull request :)

Any issues let me know!

**Comment by SUTHERLANDesign** [comment]
@hailwood Done edit and submit the pull request. Hope that is okay. :)

**Comment by hailwood** [comment]
Hey @buffy999,

It looks like the pull request hasn't yet come through, did you want to try again?

**Comment by SUTHERLANDesign** [comment]
@hailwood, ahh have just pull request now, couldn't work out before. Lol. :)
